name: Build Claude

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: "App version"
        required: false
        default: "1.0.0"
        type: string

jobs:
  build:
    uses: ./.github/workflows/pake-cli-full.yaml
    with:
      url: https://claude.ai/
      name: claude
      title: Claude
      new_window: true
      dark_mode: true
      maximize: true
      linux_targets: deb
      windows_targets: x64
      macos_targets: universal
      app_version: ${{ inputs.app_version }}
